### ISSUE TITLE
Unable to load ini file.

### ISSUE THREAD

**Issue by Ndawen** [tetele/superslicer-profiles#8] opened 2021-09-27 10:16 UTC
When I move the blv.ini file into the directory superslicer will not run gives an error code.

**Comment by tetele** [comment] 2021-09-27 11:07
Can you please provide the error code, along with the version of SuperSlicer that you are using?

**Comment by Ndawen** [comment] 2021-09-30 10:53
version 2.3.56.9
Failed loading config bundle "C:\Users\David\AppData\Roaming\SuperSlicer\vendor\BLV.ini"
Error: "'=' character not found in line" at line 7

**Comment by tetele** [comment] 2021-10-01 14:05
Have you edited the `BLV.ini` file in any way? [Line 7](https://github.com/tetele/superslicer-profiles/blob/master/BLV.ini#L7) should be empty and I cannot reproduce the issue on my machine with the same SS version.

**Comment by Ndawen** [comment] 2021-10-01 20:12
No sir no editing. What should line 7 say ?

**Comment by Ndawen** [comment] 2021-10-01 20:14
I’ll download the file again somehow it’s became corrupted.

**Comment by tetele** [comment] 2021-10-05 08:44
Any news here @Ndawen? Can I close the issue?

**Comment by Ndawen** [comment] 2021-10-05 09:46
Sorry I got busy printing. Yes it works now . Thank you so much for the profile.

**Closed as completed** 2021-10-05 09:52 UTC
